object frmP2PChat: TfrmP2PChat
  Left = 0
  Top = 0
  Caption = 'P2P'#32842#22825
  ClientHeight = 617
  ClientWidth = 1188
  Color = clBtnFace
  DoubleBuffered = True
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnClose = FormClose
  PixelsPerInch = 96
  TextHeight = 13
end
